title: Allen Snook's Blog
author: allendavidsnook
email: allen@allensnook.com
theme: minima
description: Engineering the Internet of All the Things

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
